#' Creates a client record including basic demographics
#'
#' @return a single row tibble containing client demographics
#' @export
#'
#' @examples
#' purrr::rerun(20, create_client()) %>%
#' do.call(rbind.data.frame, .)
create_client <- function() {
  gender <- sample(c("male", "female"), 1, prob = c(.4, .6))
  tibble::tibble(client_id = paste0(sample(0:9, 12), collapse = ""),
         first_name = randomNames::randomNames(1,
                                               gender = ifelse(gender == "male", 0, 1),
                                               which.names = "first"),
         last_name = randomNames::randomNames(1, which.names = "last"),
         dob = wakefield::dob(1, start = Sys.Date() - 365 * 20),
         gender = gender,
         cisgender_flag = sample(c(TRUE, FALSE), 1, prob = c(.9, .1)),
         atsi_flag = sample(c(TRUE, FALSE), 1, prob = c(.1, .9)),
         homeless_flag = sample(c(TRUE, FALSE), 1, prob = c(.05, .95)),
         translator_required = sample(c(TRUE, FALSE), 1, prob = c(.05, .95)),
         home_language = wakefield::language(1, prob = c(.00408, .6, rep(.4/98, 97)))

  )
}


#' Creates a contact episode
#'
#' @param client_id a client ID
#'
#' @return a single row tibble containing one contact episode
#'
#' @examples
#' demo <- create_client(1)
#' create_contact(demo)
create_contact <-  function(client_id) {

  dist <- dnorm(1:181, mean = 2*12, sd = 36) + dnorm(1:181, mean = 15*12, sd = 36)
  dist <- dist/sum(dist)

  tibble(client_id = client_id,
         contact_id = paste0(sample(0:9, 12), collapse = ""),
         contact_date = wakefield::date_stamp(1, start = Sys.Date() - lubridate::dmonths(24)),
         contact_time = wakefield::time_stamp(1, x = seq(7, 22, by = 5/60), prob = dist),
         hours_use = rpois(1, 0.2),
         minutes_use = sample(c(10, 15, 20, 30, 45), 1, replace = TRUE,
                              prob = c(.15, .15, .15, .4, .15))
         )

}

#' Create a dataframe of contact episodes
#'
#' @param df a data frame of consumer demographics containing a client_id
#'
#' @return a dataframe of service contact episodes where the count of episodes pre client is poisson distributed.
#' @export
#'
#' @examples
#' demo <- create_client(1)
#' contact <- create_contacts(demo)
create_contacts <- function(df){

  i <- rep(df$client_id, times = rpois(length(df$client_id), lambda = 3))
  purrr::map_df(i, create_contact)

}

#' Adds a service contact location to a service contacts dataframe
#'
#' @param contacts a dataframe of service contacts
#'
#' @return the input dataframe augmented with a service site
#' @export
#'
#' @examples
#' demo <- create_client(1)
#' contact <- create_contacts(demo)
#' contact <- localise_clients(contact)
localise_clients <- function(contacts) {

  n = length(unique(contacts$client_id))

  idx <- contacts %>% distinct(client_id) %>%
    mutate(service_location = sample(c("Agloe", "Argleton", "Mawdesky", "Bielefeld"),
                                     n, replace = TRUE)
    )

  contacts %>% dplyr::left_join(idx, by = "client_id")
}

#' Create a dataframe of intake forms
#'
#' @param contacts a dataframe of service contacts
#'
#' @return a dataframe of intake forms
#' @export
#'
#' @examples
#' demo <- create_client(1)
#' contact <- create_contacts(demo)
#' contact <- localise_clients(contact)
#' create_intakes(contact)
create_intakes <- function(contacts){

    rows <- length(unique(contacts$client_id))

  contacts %>%
    dplyr::group_by(client_id) %>%
    dplyr::slice(1) %>%
    dplyr::ungroup() %>%
    dplyr::select(-service_location) %>%
    dplyr::rename(measure_date = contact_date,
      measure_time = contact_time) %>%
    dplyr::mutate(iar_level = sample(1:5, rows,
                         prob = dbinom(0:4, size = 4, prob = .5),
                         replace = TRUE),
           presenting_concern = sample(c("Anxiety", "Depression", "AOD", "Burnout", "Insufficient cats"),
                                       size = rows, prob = c(.3, .3, .2, .19, .01), replace = TRUE)
    )
}

#' Creates a dataframe of entry and exit k10s
#'
#' @param contacts a dataframe of contacts generated by create_contacts()
#' @param intakes a dataframe of contacts generated by create_intakes()
#'
#' @return a dataframe of entry and exit k10s
#' @export
#'
#' @examples
#' demo <- create_client(1)
#' contact <- create_contacts(demo)
#' contact <- localise_clients(contact)
#' intakes <- create_intakes(contact)
#' create_k10s(contact, intakes)
create_k10s <- function(contacts, intakes) {

  contacts %>%
    dplyr::group_by(client_id) %>%
    dplyr::arrange(client_id, contact_date) %>%
    dplyr::slice(1, n()) %>%
    dplyr::distinct(contact_id, .keep_all = TRUE) %>%
    dplyr::mutate(idx = 1:n(),
                  idx = ifelse(idx == 1, "entry", "exit"),
                  dplyr::across(dplyr::everything(), as.character)) %>%
    tidyr::pivot_longer(contact_id:service_location) %>%
    dplyr::mutate(name = paste0(idx, "_", name)) %>%
    dplyr::select(-idx) %>%
    tidyr::pivot_wider(names_from = name, values_from = value) %>%
    dplyr::left_join(select(intakes, client_id, iar_level)) %>%
    dplyr::mutate(iar_level = case_when(iar_level == 1 ~ 1.5,
                                 iar_level == 2 ~ 2.3,
                                 iar_level == 3 ~ 3,
                                 iar_level == 4 ~ 3.75,
                                 iar_level == 5 ~ 4.3),
           entry_k10_total = ranger(iar_level * 10 + rnorm(n(), 0, 2),
                                    decimals = 0, min = 10, max = 50),
           exit_k10_total = ranger(entry_k10_total - rnorm(n(), 10, 7),
                                   decimals = 0, min = 10, max = 50),
           exit_k10_total = ifelse(is.na(exit_contact_id), NA, exit_k10_total),
           dplyr::across(dplyr::everything(), as.character)) %>%
    dplyr::select(-iar_level) %>%
    tidyr::pivot_longer(cols = entry_contact_id:exit_k10_total,
                        names_to = c("measure", "name"),
                        names_pattern = "(.+?)_(.+)") %>%
    ungroup() %>%
    tidyr::pivot_wider() %>%
    tidyr::drop_na(contact_id) %>%
    readr::type_convert() %>%
    dplyr::mutate(k10_01 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_02 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_03 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_04 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_05 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_06 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_07 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_08 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_09 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_10 = ranger(((k10_total + rnorm(n(), 0, 5)) / 10), 0, 1, 5),
                 k10_11 = rpois(n(), 2),
                 k10_12 = rpois(n(), 5),
                 k10_13 = rpois(n(), 1),
                 k10_14 = ranger(rpois(n(), 2), 0, 1, 5)
                 ) %>%
    dplyr::select(-k10_total) %>%
    dplyr::select(client_id, contact_id, contact_date, contact_time, service_location, measure, everything())

  }

